### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by mobileink** [ahrefs/ocaml-sodium#1]
Hi,

I see that dsheets just responded to your [request to take over maintenance of ocaml-sodium ](https://github.com/dsheets/ocaml-sodium/issues/48).  Does that offer still stand?  Should I treat this repo as the official ocaml-sodium repo?

Thanks,

Gregg

**Comment by cyberhuman** [comment]
Yes it does. Why?

**Comment by mobileink** [comment]
Just wanted to make sure you still intended to handle maintenance.  I'm adding Bazel support to ocaml-sodium if you're interested.  I'll have it up on github in an hour or so.

**Comment by mobileink** [comment]
The bazelized fork is at https://github.com/obazl/ocaml-sodium.  The Bazel rules need a little more work, then I'll submit a PR. In the meantime feel free to explore it and hit me with any questions.

Gregg

**Comment by mobileink** [comment]
PS. I forgot that I need to push my Bazel rules, it won't build until I do, which I'll get to in an hour or so.

**Comment by cyberhuman** [comment]
I'm sorry to bring the bad news here, but have you seen that this project was migrated to dune last year?

**Comment by mobileink** [comment]
Sure, that's no problem.  Bazel can coexist with any other build system.
In fact the project I'm working on builds ocaml-sodium with dune.

**Comment by cyberhuman** [comment]
Then I don't understand why yet another other build system is needed.
